version: '3.1'
services:
  gradlew-builder:
    build:
      context: .
      dockerfile: docker/Dockerfile.gradlew
    volumes:
      - "~/.gradle/caches:/root/.gradle/caches:rw"
      - "~/repo:/usr/src/app:rw"
    depends_on:
      - "adoption_service_postgres"
  adoption_service_postgres:
    image: "postgres:10"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=animal_adoption_db