version: '3.7'
services:
  adoption-service:
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    image: adoption-service
    ports:
      - "8080:8080"
    depends_on:
      - adoption-service-db
    # TODO: Add health check for adoption service

  adoption-service-builder:
    build:
      context: .
      dockerfile: docker/Dockerfile-builder
    volumes:
      - ./.docker-gradle-build-cache:/home/gradle/.gradle:rw

  adoption-service-db:
    build:
      context: .
      dockerfile: docker/Dockerfile-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD", "psql", "-U", "admin", "-d", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 3

  wiremock:
    image: rodolpheche/wiremock:latest
    ports:
      - "8123:8080"
    volumes:
      - ./docker/wiremock/stubs:/home/wiremock:ro
    command: ["java", "-cp", "/var/wiremock/lib/*:/var/wiremock/extensions/*",
              "com.github.tomakehurst.wiremock.standalone.WireMockServerRunner",
              "--global-response-templating"]
