version: '3.7'
services:
  adoption-service:
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    image: adoption-service
    ports:
      - "8080:8080"
    depends_on:
      - adoption-service-db
    environment:
      SPRING_PROFILE: docker
    # TODO: Add health check for adoption service

  adoption-service-builder:
    build:
      context: .
      dockerfile: docker/Dockerfile-builder
    environment:
      SPRING_PROFILE: docker
      ADOPTION_SERVICE_URL: http://adoption-service:8080
      ADMIN_JWT:
    volumes:
      - ~/.gradle/caches:/home/gradle/.gradle/caches:rw

  adoption-service-db:
    build:
      context: .
      dockerfile: docker/Dockerfile-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD", "psql", "-U", "admin", "-d", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 3