server:
  servlet:
    context-path: /adoption

spring:
  datasource:
    hikari:
      connection-timeout: 2000
      validation-timeout: 500
      leak-detection-threshold: 2000
      max-lifetime: 300000
      maximum-pool-size: 1
  jpa:
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    locations: classpath:db/migration
  jackson:
    default-property-inclusion: NON_EMPTY
    serialization:
      write_dates_as_timestamps: false
  sql:
    init:
      platform: postgres

resilience4j.circuitbreaker:
    instances:
      media-repository:
        failureRateThreshold: 50
        slowCallRateThreshold: 60
        slowCallDurationThreshold: 5000
        permittedNumberOfCallsInHalfOpenState: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 20
        waitDurationInOpenState: 60000
        automaticTransitionFromOpenToHalfOpenEnabled: false