spring:
  profiles: ci
  cloud:
    gcp:
      config.enabled: true
      logging.enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}
    username: ${CI_SQL_CLOUD_MASTER_USERNAME}
    password: ${CI_SQL_CLOUD_MASTER_PASSWORD}


google.cloud.storage.bucket: ${CI_ANIMAL_PICTURES_BUCKET}

logging:
  config: classpath:logback-spring-ci.xml