logging:
  level:
    root: WARN

server:
  port: 8080
  servlet:
    path: /adoption

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/animal_adoption_db
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: create-drop
  flyway:
    locations: classpath:db/migration
  jackson:
    serialization:
      write_dates_as_timestamps: false