spring:
  datasource:
    username: ${CI_SQL_CLOUD_MASTER_PASSWORD}
    password: ${CI_SQL_CLOUD_MASTER_USERNAME}
    url: jdbc:postgresql://google/animal_adoption_db?socketFactory=com.google.cloud.sql.postgres.SocketFactory&socketFactoryArg=${DB_CONNECTION_NAME}

google:
  cloud:
    storage:
      bucket: animal-pictures-store