spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}
    username: ${CI_SQL_CLOUD_MASTER_USERNAME}
    password: ${CI_SQL_CLOUD_MASTER_PASSWORD}


google:
  cloud:
    storage:
      environment: ${SPRING_PROFILE}
      bucket: ${CI_ANIMAL_PICTURES_BUCKET}