spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://adoption-service-db:5432/animal_adoption_db
    username: adoption_service
    password: adoption_service
    test-on-borrow: true
    test-while-idle: true
    validation-query: select 1;
    maxActive: 50
    master:
      username: admin
      password: admin
  jpa:
    show-sql: false
    generate-ddl: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://wiremock:8080/

cloudinary:
  cloud-name: cloudinary-dummy-cloud-name
  api-key: cloudinary-dummy-api-key
  api-secret: cloudinary-dummy-secret
  upload-prefix: http://wiremock:8080/

logging:
  config: classpath:logback-spring-docker.xml