logging:
  level:
    root: WARN

server:
  port: 8080
  servlet:
    path: /adoption

spring:
  datasource:
    platform: postgres
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  flyway:
    locations: classpath:db/migration
  jackson:
    default-property-inclusion: NON_EMPTY
    serialization:
      write_dates_as_timestamps: false