spring:
  profiles: dev
  cloud:
    gcp:
      config.enabled: false
      storage.enabled: false
      logging.enabled: false
      sql.enabled: false
  datasource:
    url: jdbc:postgresql://adoption-service-db:5432/animal-adoption-db
    username: postgres
    test-on-borrow: true
    test-while-idle: true
    validation-query: select 1;
    maxActive: 50
  jpa:
    show-sql: false
    generate-ddl: false

google.cloud.storage.bucket: adoption-service-testing

logging:
  config: classpath:logback-spring-dev.xml