server:
  port: 8080

spring:
  mvc:
    servlet:
      path: /adoption
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 10
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    locations: classpath:db/migration
  jackson:
    default-property-inclusion: NON_EMPTY
    serialization:
      write_dates_as_timestamps: false
  security:
    basic:
      enabled: false

auth0:
  audience: https://animales-rescatados/servicio-adopciones.ec

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
