spring:
  datasource:
    url: jdbc:postgresql://adoption-service-db:5432/animal-adoption-db
    username: postgres
    password: p0stgr3s
    test-on-borrow: true
    test-while-idle: true
    validation-query: select 1;
    maxActive: 50
  jpa:
    show-sql: false
    generate-ddl: false

google:
  cloud:
    storage:
      environment: dev
      bucket: adoption-service-testing