spring:
  profiles: live
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://emmeblm.auth0.com/

cloudinary:
  url: ${CLOUDINARY_URL}

logging:
  config: classpath:logback-spring-live.xml