logging:
  level:
    root: WARN

server:
  port: 4545
  servlet:
    path: /adoption

spring:
  datasource:
    platform: postgres
  jpa:
    open-in-view: false
  flyway:
    locations: classpath:db/migration
  jackson:
    default-property-inclusion: NON_EMPTY
    serialization:
      write_dates_as_timestamps: false