spring:
  datasource:
    username: postgres
    password: ${jdbc.password}
    url: jdbc:postgresql://google/animal_adoption_db?socketFactory=com.google.cloud.sql.postgres.SocketFactory&socketFactoryArg=${jdbc.connection_name}

google:
  cloud:
    storage:
      bucket: animal-pictures-store