spring:
  config:
    activate:
      on-profile: uat
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_RESOURCE_SERVER_ISSUER_URI}

auth0:
  audience: ${AUTH0_AUDIENCE}
  custom-claims:
    organization-id: ${AUTH0_CUSTOM_CLAIM_ORG_ID}

logging:
  config: classpath:logback-spring-heroku.xml