spring:
  profiles: live
  datasource:
    url: ${DATABASE_URL}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://emmeblm.auth0.com/

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

logging:
  config: classpath:logback-spring-live.xml