spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/animal_adoption_db
    username: adoption_service
    password: adoption_service
    test-on-borrow: true
    test-while-idle: true
    validation-query: select 1;
    maxActive: 50
    master:
      username: admin
      password: admin
  jpa:
    show-sql: false
    generate-ddl: false
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8123/

auth0:
  audience: https://dummy/dummy.ec
  custom-claims:
    organization-id: https://dummy/organization_id

cloudinary:
  cloud-name: cloudinary-dummy-cloud-name
  api-key: cloudinary-dummy-api-key
  api-secret: cloudinary-dummy-secret
  upload-prefix: http://localhost:8123/

logging:
  config: classpath:logback-spring-local.xml