spring:
  profiles: ci
  cloud:
    gcp:
      config.enabled: true
      storage.enabled: true
      logging.enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}
    username: ${CI_SQL_CLOUD_MASTER_USERNAME}
    password: ${CI_SQL_CLOUD_MASTER_PASSWORD}
    master:
      username: ${CI_SQL_CLOUD_MASTER_USERNAME}
      password: ${CI_SQL_CLOUD_MASTER_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://emmeblm.auth0.com/

auth0:
  audience: https://animales-rescatados/servicio-adopciones.ec

google.cloud.storage.bucket: ${CI_ANIMAL_PICTURES_BUCKET}

logging:
  config: classpath:logback-spring-ci.xml