version: 2.1

####################
# Orbs & Executors
####################

orbs:
  heroku: circleci/heroku@1.2.6

executors:
  builder:
    docker:
      - image: cimg/openjdk:11.0

####################
# Jobs
####################

jobs:
  build:
    executor: builder
    resource_class: large
    parallelism: 8
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.gradle" }}
            - v2-dependencies-

      - run:
          name: Running unit tests in parallel
          command: |
            cd src/test/java
            # Get list of classnames of tests that should run on this node
            CLASSNAMES=$(circleci tests glob "**/*Test.java" \
              | cut -c 1- | sed 's@/@.@g' \
              | sed 's/.\{5\}$//' \
              | circleci tests split --split-by=timings --timings-type=classname)
            cd ../../..
            # Format the arguments to "./gradlew test"
            GRADLE_ARGS=$(echo $CLASSNAMES | awk '{for (i=1; i<=NF; i++) print "--tests",$i}')
            echo "Prepared arguments for Gradle: $GRADLE_ARGS"
            ./gradlew test $GRADLE_ARGS

      - run:
          name: Generate code coverage report
          command: ./gradlew jacocoTestReport

      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always

      - store_test_results:
          path: ~/test-results

      - store_artifacts:
          path: ~/test-results

      - persist_to_workspace:
          root: .
          paths:
            - src
            - scripts
            - docker
            - gradle
            - build.gradle
            - settings.gradle
            - gradlew
            - gradlew.bat
            - Dockerfile
            - docker-compose.yaml
            - Makefile
            - Procfile
            - system.properties
            - .gitignore
            - .git
            - build/reports/jacoco

  pitest:
    executor: builder
    resource_class: large

    steps:
      - attach_workspace:
          at: .

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.gradle" }}
            - v2-dependencies-

      - run:
          name: Run pitest analysis
          command: ./gradlew pitest

      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "build.gradle" }}

      - store_artifacts:
          path: build/reports/pitest

  sonar:
    executor: builder
    resource_class: large

    steps:
      - attach_workspace:
          at: .

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.gradle" }}
            - v2-dependencies-

      - run:
          name: Analyze code on SonarCloud
          command: |
            pwd
            ls -al build/
            ls -al build/reports/
            ./gradlew sonarqube

      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "build.gradle" }}

  integration-test:
    executor: builder
    resource_class: large

    steps:
      - attach_workspace:
          at: .

      - setup_remote_docker

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.gradle" }}
            - v2-dependencies-

      - run:
          name: Running integration tests
          command: make test-integration

      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/integrationTest/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always

      - store_test_results:
          path: ~/test-results

      - store_artifacts:
          path: ~/test-results

  api-test:
    executor: builder
    resource_class: large

    steps:
      - attach_workspace:
          at: .

      - setup_remote_docker

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.gradle" }}
            - v2-dependencies-

      - run:
          name: Running api tests
          command: make test-api

      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/apiTest/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always

      - store_test_results:
          path: ~/test-results

      - store_artifacts:
          path: ~/test-results

  arch-unit:
    executor: builder
    resource_class: large

    steps:
      - attach_workspace:
          at: .

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.gradle" }}
            - v2-dependencies-

      - run:
          name: Run architecture atomic fitness functions
          command: ./gradlew archUnitTest

      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/archUnitTest/.*xml" -exec cp {} ~/test-results/archunit/ \;
          when: always

      - store_test_results:
          path: ~/test-results

      - store_artifacts:
          path: ~/test-results

  deploy-uat:
    executor: heroku/default
    resource_class: large

    steps:
      - attach_workspace:
          at: .

      - heroku/deploy-via-git:
          app-name: servicio-adopciones-uat

      - heroku/install

      - run:
          name: Scaling app
          command: heroku ps:scale --app servicio-adopciones-uat web=1

  uat-integration-test:
    executor: builder
    resource_class: large

    steps:
      - attach_workspace:
          at: .

      - heroku/install

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.gradle" }}
            - v2-dependencies-

      - run:
          name: Running integration tests in uat environment
          command: |
            export SPRING_PROFILE=uat;
            export ADOPTION_SERVICE_URL="$(echo $ADOPTION_SERVICE_URL_UAT)";
            ./gradlew integrationTest

      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/integrationTest/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always

      - store_test_results:
          path: ~/test-results

      - store_artifacts:
          path: ~/test-results

  uat-api-test:
    executor: builder
    resource_class: large

    steps:
      - attach_workspace:
          at: .

      - heroku/install

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.gradle" }}
            - v2-dependencies-

      - run:
          name: Running api tests in uat environment
          command: |
            export SPRING_PROFILE=uat;
            export ADOPTION_SERVICE_URL="$(echo $ADOPTION_SERVICE_URL_UAT)";
            ./gradlew apiTest

      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/apiTest/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always

      - store_test_results:
          path: ~/test-results

      - store_artifacts:
          path: ~/test-results

####################
# Workflows
####################

workflows:
  version: 2
  adoption-service-pipeline:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - pitest:
          requires:
            - build
          filters:
            branches:
              only: master
      - sonar:
          context: SonarCloud
          requires:
            - build
          filters:
            branches:
              only: master
      - integration-test:
          requires:
            - build
          filters:
            branches:
              only: master
      - api-test:
          requires:
            - build
          filters:
            branches:
              only: master
      - arch-unit:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-uat:
          requires:
            - pitest
            - sonar
            - integration-test
            - api-test
            - arch-unit
          filters:
            branches:
              only: master
      - uat-integration-test:
          requires:
            - deploy-uat
          filters:
            branches:
              only: master
      - uat-api-test:
          requires:
            - uat-integration-test
          filters:
            branches:
              only: master