# Java Gradle CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - persist_to_workspace:
          root: ~/repo
          paths:
            - src
            - migrations
            - gradle
            - build.gradle
            - settings.gradle
            - gradlew
            - gradlew.bat

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run: ./gradlew dependencies

      - run: ./gradlew clean build

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/test/.*xml" -exec cp {} ~/test-results/junit \;
          when: always

      - store_test_results:
          path: ~/test-results/junit

      - store_artifacts:
          path: ~/test-results/junit

      - store_artifacts:
          path: build/libs/adoption-service-1.0-SNAPSHOT.jar

  pitest:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - attach_workspace:
          at: ~/repo

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run: ./gradlew clean pitest

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - store_artifacts:
          path: build/reports/pitest

  integration-test:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: postgres:10
        environment:
          POSTGRES_DB: animal_adoption_db

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgress && exit 1

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run: ./gradlew clean integrationTest

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/integrationTest/.*xml" -exec cp {} ~/test-results/junit \;
          when: always

      - store_test_results:
          path: ~/test-results/junit

      - store_artifacts:
          path: ~/test-results/junit

workflows:
  version: 2
  adoption-service:
    jobs:
      - build
      - pitest:
          requires:
            - build
          filters:
            branches:
              only: master
      - integration-test:
          requires:
            - build
            - pitest
          filters:
            branches:
              only: master