FROM adoptopenjdk/openjdk11:jre-11.0.6_10-alpine

ENV LANG C.UTF-8

EXPOSE 8080

RUN apk update && apk add postgresql
RUN psql --version
COPY scripts/wait-for-postgres.sh /api/wait-for-postgres.sh

COPY build/libs/*.jar /api/AdoptionService.jar
RUN ls /api
WORKDIR /api

CMD ./wait-for-postgres.sh adoption-service-db && java -jar -Dspring.profiles.active=docker -server -Xms256m -Xmx512m -XX:MaxMetaspaceSize=512m -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -XX:+UseTLAB AdoptionService.jar