FROM openjdk:17-jdk-alpine

ENV LANG C.UTF-8

EXPOSE 8080

RUN apk update && apk add postgresql
RUN psql --version
COPY scripts/wait-for-postgres.sh /api/wait-for-postgres.sh

COPY build/libs/*.jar /api/AdoptionService.jar
RUN ls /api
WORKDIR /api

CMD ./wait-for-postgres.sh adoption-service-db && java -jar -Dspring.profiles.active=docker -Dhibernate.types.print.banner=false AdoptionService.jar