FROM rodolpheche/wiremock:latest

COPY docker/wiremock/stubs /home/wiremock

CMD ["java", "-cp", "/var/wiremock/lib/*:/var/wiremock/extensions/*", "com.github.tomakehurst.wiremock.standalone.WireMockServerRunner", "--global-response-templating", "--verbose"]