FROM adoptopenjdk/openjdk8:jdk8u212-b04-slim

WORKDIR /usr/lib

COPY gradle/wrapper ./gradle/wrapper
COPY gradlew ./

ENV PATH "${PATH}:/usr/lib"
RUN ./gradlew --version

WORKDIR /usr/src/app
ENTRYPOINT ["gradlew"]