apiVersion: apps/v1
kind: Deployment
metadata:
  name: adoption-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adoption-service
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: adoption-service
    spec:
      containers:
        - name: adoption-service
          image: emmeblm/adoption-service:latest
          env:
            - name: SPRING_PROFILE
              value: ci
          ports:
            - containerPort: 8080